// Generated by CoffeeScript 1.3.3
(function() {
  var bus;

  bus = require('../../bus');

  'class LoginModule\n  constructor: (registerHandler, registerSubscriber) ->\n    console.log \'handler:\'\n    console.log registerHandler\n    console.log \'subscriber:\'\n    console.log registerSubscriber';


}).call(this);
