// Generated by CoffeeScript 1.6.2
(function() {
  var AgileDictionary, VocabDictionary, VocabWord;

  VocabWord = (function() {
    function VocabWord(word, definition, exampleSentence) {
      this.word = word;
      this.definition = definition;
      this.exampleSentence = exampleSentence != null ? exampleSentence : '';
    }

    return VocabWord;

  })();

  VocabDictionary = (function() {
    function VocabDictionary() {}

    VocabDictionary.prototype._words = [];

    VocabDictionary.prototype.addWord = function(word, definition, exampleSentence) {
      if (exampleSentence == null) {
        exampleSentence = '';
      }
      return this._words.push(new VocabWord(word, definition, exampleSentence));
    };

    VocabDictionary.prototype.getWord = function(index) {
      return this._words[index];
    };

    VocabDictionary.prototype.getWordByName = function(word) {
      return "var dictionaryWord = Enumerable.from(this._words).firstOrDefault(function (w) { return w.word == word; });\nreturn dictionaryWord;";
    };

    VocabDictionary.prototype.getRandomWord = function() {
      var word;

      return word = this._words[Math.floor(Math.random() * this._words.length)];
    };

    VocabDictionary.prototype.wordCount = function() {
      return this._words.length;
    };

    return VocabDictionary;

  })();

  AgileDictionary = new VocabDictionary();

  AgileDictionary.addWord('Activity', 'The task or function that when performed produce a product or service.');

  AgileDictionary.addWord('Andon board', 'A term for a visual control device that allows anyone to see and manage the status of the value stream.');

  AgileDictionary.addWord('Appreciative inquiry', 'An approach to bringing change to organizations that builds on the holistic history of positive stories and successes. It engages people to link the positives of the past with the organization\'s current capabilities to consciously construct a better future.');

  AgileDictionary.addWord('Auto-documentation', 'Building into the process the ability to automatically document both the process followed and the output of that process.');

  AgileDictionary.addWord('Backlog', 'Activities held in inventory that have yet to be initiated as work-in-process.');

  AgileDictionary.addWord('Baka yoke', 'A term for the design of a process so that it is impossible for mistakes to be made. Also known as error or mistake proofing.');

  AgileDictionary.addWord('Balanced flow', 'An approach to achieve continuous flow of a value stream by designing each of the roles of the value stream to statistically take the same amount of wall clock time to produce their value. The flow is balanced by adjusting the activities and resources assigned to each role to equalize their timing.');

  AgileDictionary.addWord('Batch', 'A collection of multiple items for processing at some future step.');

  AgileDictionary.addWord('Bottleneck', 'Any point in the value stream where the capacity to produce work is less than the work ready to be performed.');

  AgileDictionary.addWord('Burndown chart', 'A report showing the sprint task hours completed by a team during an Agile sprint.  Typically a burndown chart is updated daily.  The Y axis indicates the number of task hours remaining and the X axis indicates the time duration of the sprint.');

  AgileDictionary.addWord('Business friction', 'Barriers to workplace productivity that build when the value streams of the organization are not aligned with the four dimensions of office performance: people, process, technology, and time.');

  AgileDictionary.addWord('Capability', 'The expertise and resources necessary to produce a product or service. Example capabilities are project management, requirements analysis, training, risk management, quality assurance, etc.');

  AgileDictionary.addWord('Catch-ball', 'A consensus building, iterative process that is used in policy deployment to develop the vital few initiatives to link organizational strategy to its execution.');

  AgileDictionary.addWord('Complex system', 'A holistic view that recognizes everything is connected to everything else. For example, business environments are complex systems where you can\'t just do one thing; that every action has various planned and unplanned reactions. Lean process improvement is an approach to improve the performance of complex business systems while reducing the risk of unintended consequences.');

  AgileDictionary.addWord('Constraint', 'Anything that limits a value stream from achieving higher performance; i.e., throughput, cycle time, quality.');

  AgileDictionary.addWord('Continuous flow', 'A value stream that experiences no wait states. In a state of continuous flow the work time and the service time of a value stream are identical.');

  AgileDictionary.addWord('Continuous performance improvement', 'An approach that engages employees in an unrelenting focus on improving the effectiveness and efficiencies of the value streams of an organization.');

  AgileDictionary.addWord('Cost of non-quality', 'The financial impact due to the production of waste by the organization. Here waste refers to all seven wastes and their financial impact, not just the waste of defects.');

  AgileDictionary.addWord('Current state value stream', 'a snapshot view of a value stream as it exists at the time of observation.');

  AgileDictionary.addWord('Customer', 'The internal or external recipient of the value produced by an upstream role of a value stream. ');

  AgileDictionary.addWord('Customer value', 'Something of worth in usefulness or importance to a customer. Sometimes used interchangeably with stakeholder value.');

  AgileDictionary.addWord('Cycle time', 'The wall clock time necessary to complete a single item of work. For example, the cycle time to enter the data for one order is the wall clock time from when the data entry starts until it is complete.');

  AgileDictionary.addWord('Effectiveness', 'Maximizing the overall performance of a value stream. Sometimes there is a tradeoff where increasing effectiveness causes reduced efficiency of certain individual activities.');

  AgileDictionary.addWord('Efficiency', 'Maximizing the performance of a single activity of a value stream. Sometimes there is a tradeoff where increasing efficiency causes reduced effectiveness of the overall performance of the value stream.');

  AgileDictionary.addWord('Epic', 'A large story that is too big to be completed in a single Agile sprint.  Epics are useful as placeholders for lower priority requirements in the backlog.');

  AgileDictionary.addWord('Error proofing', 'Building into the value stream the ability to prevent errors from occurring and/or the ability to immediately recognize errors when they occur.');

  AgileDictionary.addWord('Feedback', 'The output of an activity that in turn causes a positive or negative reinforcement for other activities. An example of a positive feedback loop is that selling razors increases the number of razor blades sold. An example of a negative feedback loop is that building roads increases traffic congestion. Feedback is an important aspect in designing effective and efficient value streams.');

  AgileDictionary.addWord('First in, first out', 'The order something is taken from a queue or batch; also known as FIFO.');

  AgileDictionary.addWord('Flow', 'The movement of items of value from one role to the next in a value stream.');

  AgileDictionary.addWord('Future state value stream', 'a snapshot view of a value stream as it might appear to an observer at some point in the future.');

  AgileDictionary.addWord('Gemba', 'A term for the workspace of an organization. The workspace is an important concept in Lean process improvement because it is the location where customer value is created.');

  AgileDictionary.addWord('Hoshin kanri', 'A term for a top down planning process that ties strategic direction to the vital few tactical initiatives for executing the desired strategy. Also known as strategy or policy deployment.');

  AgileDictionary.addWord('Information radiator', 'A visual display of information about an Agile project that can easily be consumed without the need to interrupt anyone for status.  See Kanban.');

  AgileDictionary.addWord('Inventory', 'Material or information resources waiting to be consumed in the production of customer value. ');

  AgileDictionary.addWord('ISO 9000:2000', 'Specifies requirements for a quality management system for any organization that needs to demonstrate its ability to consistently provide a product or service that meets stakeholder and/or applicable regulatory requirements.');

  AgileDictionary.addWord('Iron Triangle', 'When applied to project management indicates a situation where all three project constraints of cost, scope, and time are fixed at the start of the project.');

  AgileDictionary.addWord('Just-in-time', 'The assets or activities of a value stream becoming available or occurring just as they are needed.');

  AgileDictionary.addWord('Kaizen', 'A term for incremental improvement. Kaizen is a people and process oriented way of thinking as opposed to problem and solution oriented thinking.  See Kaizen workshop.');

  AgileDictionary.addWord('Kaizen workshop', 'A term for workshops to identify and implement improvements to a value stream.  Lean Kaizens are typically a week in duration.');

  AgileDictionary.addWord('Kanban', 'A term for a visual indicator that indicates when to execute an activity in a value stream.  A version of Kanban boards may also be used as information radiators to provide visibility to an Agile sprint backlog and work-in-process.');

  AgileDictionary.addWord('Kitting', 'A term for collecting all of the required assets into a work-in-process kit to support a role of a value stream.');

  AgileDictionary.addWord('Last in, first out', 'The order something is taken from a queue or batch; also known as LIFO.');

  AgileDictionary.addWord('Lead time', 'The time from when a customer request is made for a product or service until the request is fulfilled.');

  AgileDictionary.addWord('Lean', 'An umbrella term for a powerful combination of techniques to maximize customer value while minimizing waste and achieving continuous flow through a sustainable culture of continuous improvement. This term is used in the U.S. for what was originally created as the "Toyota Production System".');

  AgileDictionary.addWord('Lean office', 'The application of Lean techniques in an office environment.');

  AgileDictionary.addWord('Lean production', 'A manufacturing approach attributed to Taiichi Ohno of Toyota in the early 1950s. It defines work as a series of steps performed by cross-functional teams under distributed control; with the standardization of each of the five Ms of operational performance.');

  AgileDictionary.addWord('Lean ratio', 'Wait Time / Work Time. The ratio of wait time to work time is a measure of the efficiency of a process flow.  A process that achieves continuous flow has a perfect ratio of 1.  Any process with this ratio less than 2 is considered a conforming process. Typical processes in a non-conforming environment have this ratio closer to 10 and above.');

  AgileDictionary.addWord('Matrix management', 'An organizational structure that establishes roles and responsibilities for each value domain of the organization. Matrix management structures can have varying levels of formality; from generally understood but unwritten responsibilities, to organizational charters documenting specific cross-domain roles and responsibilities in detail. Value domains may include geographies, products/services, customers/stakeholders, employees, or functions.');

  AgileDictionary.addWord('Mass customization', 'The ability to produce a high volume throughput that is tailored to every consumer of the product or service.');

  AgileDictionary.addWord('Mass production', 'A manufacturing approach attributed to Henry Ford in the early 1900s. It defines work as a series of specialized activities under centralized control; with the standardization of product components. Today mass production is still the foundation of most the office environments.');

  AgileDictionary.addWord('Mistake proofing', 'Building into the value stream the ability to prevent errors from occurring and/or the ability to immediately recognize errors when they occur.');

  AgileDictionary.addWord('Monument', 'A role or tool within a value stream that is very expensive to operate and maintain. As a result the organization feels it must insure the monument is always busy to maximize its return-on-investment. This can lead to the wastes of waiting, overproduction, transportation, work-in-process, and underutilization.');

  AgileDictionary.addWord('Muda', 'A term for waste.');

  AgileDictionary.addWord('Non-value add', 'All or a portion of an activity that produces waste.');

  AgileDictionary.addWord('Outcome', 'A measureable result produced by a value stream that has value a customer would pay for.');

  AgileDictionary.addWord('PDCA', 'A four stages cycle of continuous improvement popularized by W. Edward Deming.');

  AgileDictionary.addWord('Performance principles', 'A rule or standard used to align day-to-day tactical decision making with the organization\'s strategy and value statements. Value statements establish worth; a principle is a standard for achieving that worth. If values are the what; principles are the how.');

  AgileDictionary.addWord('Poka yoke', 'A term that means mistake proofing.');

  AgileDictionary.addWord('Policy deployment', 'A term for a top down planning process that ties strategic direction to the vital few tactical initiatives for executing the desired strategy. Also known as Hoshin kanri or strategy deployment.');

  AgileDictionary.addWord('Policy intervention', 'The tendency for an initiative to be delayed, diluted, or defeated by the natural feedback responses of the system to the initiative itself.');

  AgileDictionary.addWord('Principle', 'A rule or standard; especially of good behavior.');

  AgileDictionary.addWord('Product backlog', 'An inventory of Agile project/product stories defining an improvement project stacked ranked by priority that have not yet been selected for an Agile sprint.  A project backlog may include both software product related stories as well as project stories not related to a software product.');

  AgileDictionary.addWord('Product owner', 'Defines a role in an Agile project that is responsible for maintaining the product backlog.');

  AgileDictionary.addWord('Productivity', 'The ratio of customer value produced per unit of labor. For example, productivity can be measured as the transactions per employee hours worked or burdened labor invested.');

  AgileDictionary.addWord('Process', 'Rules for performing activities. Process rules describe when an activity is to be performed, how it is performed, and what resources should be used.');

  AgileDictionary.addWord('Pull system', 'When a downstream role of a value stream pulls work from the role or store that is directly upstream. This is the opposite of a push system.');

  AgileDictionary.addWord('Push system', 'When the upstream role of a value stream pushes work to the role or store that is directly downstream. This is the opposite of a pull system.');

  AgileDictionary.addWord('Quality', 'The continuous improvement of the effectiveness and efficiency of value added work, while reducing or eliminating waste or non-value added work.');

  AgileDictionary.addWord('Queue', 'A physical store for items as they wait for the next action in a value stream.');

  AgileDictionary.addWord('Ramp-up time', 'The wall clock time it takes from starting an activity until full productivity for that activity is reached.');

  AgileDictionary.addWord('Resource', 'The assets of the organization including: people, processes, technologies, materials, and time. ');

  AgileDictionary.addWord('Right sizing', 'Assigning resources to a value stream such that they are just sufficient to perform a balanced flow of work throughout that value stream.');

  AgileDictionary.addWord('Role', 'A self-contained collection of assigned activities performed by one or more individuals of an organization. A role is defined by its ability to complete all activities assigned to the it without the need to interrupt the work and transfer ownership for any of the assigned activities to anyone else.');

  AgileDictionary.addWord('Sashimi', 'An Agile concept of delivering value in slices rather than in layers/stages.  An Agile Story is sashimi because it can be proven it is done.  It is not possible to prove that a requirements document is done.');

  AgileDictionary.addWord('Scrum', 'A lightweight framework for managing complex projects.  Scrum is one of a number of methodologies under the Agile umbrella.  Scrum was originally developed to guide complex software projects.  Scrum delivers incremental iterative time-boxed sprints that deliver value early and often.');

  AgileDictionary.addWord('ScrumMaster', 'Defines a role in an Agile project that is responsible for the successful completion of the sprint.  A Scrum Master facilitates communication and helps to remove impediments to sprint performance.');

  AgileDictionary.addWord('Segregate complexity', 'Establishing parallel branches in a value stream based on the complexity of the work performed. Each branch can then be optimized for the complexity of work assigned.');

  AgileDictionary.addWord('Service time', 'SWork Time + Wait Time. Defines the two contributing components of service time from the perspective of information or material flow rather than a person or tool. For example, the service time to data enter one order is the time from when the order is received on the data entry person\'s desk until the time the order has been data entered and is moved off the desk to the next step in the flow. The service time includes both the time the order is waiting to be worked on during that period as well as the actual time it is worked on.');

  AgileDictionary.addWord('Seven office wastes', 'Categories of non-value added office activities.');

  AgileDictionary.addWord('Defect', 'An error that requires rework.');

  AgileDictionary.addWord('Underutilization', 'Office resources not fully used to their capacity.');

  AgileDictionary.addWord('Transportation', 'Moving a resources from one place to another.');

  AgileDictionary.addWord('Waiting', 'Inactive resources.');

  AgileDictionary.addWord('Variation', 'Using multiple methods to produce the same value.');

  AgileDictionary.addWord('Work-in-process', 'Any product or service started but not completed.');

  AgileDictionary.addWord('Overproduction', 'Producing anything before it is needed.');

  AgileDictionary.addWord('Silo', 'A term describing a functional area of an organization. For example a customer service department, that has very little communication or integration with other functional areas. A "silo view" is the opposite of a "system-wide view."');

  AgileDictionary.addWord('Six sigma', 'A statistical approach for measuring variability.');

  AgileDictionary.addWord('Span-of-coordination', 'The reach of an individual\'s or team\'s responsibilities, involving both leadership and support responsibilities, in addition to authority (span-of-control). Span-of-coordination is an important concept for maintaining the system-wide performance of value streams.');

  AgileDictionary.addWord('Sprint', 'A single time-boxed iteration of an Agile project.  Sprints may be of any duration (i.e., two weeks or two months) but typically are of a fixed duration for every iteration of a project.');

  AgileDictionary.addWord('Sprint Backlog', 'An inventory of Agile tasks that have been selected for an Agile sprint.');

  AgileDictionary.addWord('State', 'A snapshot view that provides an observer the picture of the situation.');

  AgileDictionary.addWord('Stakeholder', 'Any party that has an interest in the product/service produced by an organization\'s value stream.');

  AgileDictionary.addWord('Stakeholder value', 'The worth of the stakeholder\'s interest in the product/service produced by an organization\'s value stream. Sometimes used interchangeably with customer value.');

  AgileDictionary.addWord('Stop-the-line', 'An approach to managing a value stream that allows anyone to halt work while defects are occurring so they are not propagated through the system.');

  AgileDictionary.addWord('Store', 'A place to store the inventory or work-in-process of a value stream. Stores may include information systems storing information, queue storing paper, or bins storing materials.');

  AgileDictionary.addWord('Story', 'A token representing a project or product requirement, typically stated in the form: As a <user or role>,I want <business functionality>, So that <business benefit>.');

  AgileDictionary.addWord('Story points', 'A method for estimating the size of an Agile story used as an alternative to estimating the story in hours.  Story points compare one story to another to determine a relative size and then assign points denoting that size.  The anticipated velocity of a sprint team is then used to estimate how many story points they can deliver in a sprint.');

  AgileDictionary.addWord('Strategy deployment', 'A term for a top down planning process that translates strategic direction into the vital few tactical initiatives for strategy realization. Also known as Hoshin kanri or policy deployment.');

  AgileDictionary.addWord('Supermarket', 'A collection of a queues where the minimum and maximum amount of inventory or work-in-process that can be stored in each queue is regulated. Supermarkets can form the boundaries between push and pull systems of a value stream.');

  AgileDictionary.addWord('System-wide view', 'Evaluating the performance of the organization by considering the complex interactions between all of the activities that produce customer value – not just those of a single functional department or product line.');

  AgileDictionary.addWord('Takt time', 'A term for the beat or rhythm of the activities that make up a value stream. For example suppose the takt time of a value stream is set at 30 minutes. This means that the activities are designed and resourced to complete every role of the value stream in 30 minutes. When every role of a value stream executes to the same beat or takt time, the output of each upstream role is finished at the same time each downstream role becomes ready for its input. This helps to achieve a balanced flow.');

  AgileDictionary.addWord('Task', 'A discrete unit of work.  Agile stories are broken down into a collection of tasks that must be performed to complete the story in one sprint.  Tasks are typically sized to represent 4 to 8 hours of labor.');

  AgileDictionary.addWord('Theory of constraints', 'Streamlines operations by focusing on end-to-end throughput effectiveness, not individual efficiency. Seeks to identify bottlenecks and provide alternatives for their elimination.');

  AgileDictionary.addWord('Throughput', 'The velocity of work performed by a value stream. Throughput counts the units of customer value produced for a given time period.');

  AgileDictionary.addWord('Time-boxed', 'There are three constraints of any project: cost, scope, and time.  A time-boxed project fixes time and allows cost and scope to vary to meet the time.  An Agile project is delivered in time-boxed iterations that are fixed in calendar time.');

  AgileDictionary.addWord('Theme', 'A collection of Agile stories that have a common affinity.');

  AgileDictionary.addWord('Total Cycle Time', 'The sum of the cycle times for all of the discrete cycle times for role or value stream. Equivalent in this usage to "service time."');

  AgileDictionary.addWord('Toyota production system', 'The various techniques developed by Taiichi Ohno of Toyota to increase manufacturing performance. Outside of Toyota these techniques are better known as Lean.');

  AgileDictionary.addWord('Value', 'Something of worth in usefulness or importance to the possessor. Note that value is determined by the recipient of the product/service not the producer.');

  AgileDictionary.addWord('Value add', 'The activities that transform the resources of an organization into a product or service someone is willing to pay for.');

  AgileDictionary.addWord('Value matrix', 'A matrix that is defined for each of an organization\'s value domains. Value domains may include geographies, products/services, customers/stakeholders, employees, or functions.');

  AgileDictionary.addWord('Value priorities', 'The relative ranking of the stakeholder values generated by a value stream.');

  AgileDictionary.addWord('Value statement', 'Establishes the way or direction that stakeholder worth or usefulness is created by an organization. Value statements say what the organization is committed to do. In contrast, principle statements say how the organization is going to do it.');

  AgileDictionary.addWord('Value stream', 'A holistic collection of value added and non-value added activities that are chained together to create customer value in terms of a product or service.');

  AgileDictionary.addWord('Value stream map', 'The graphical documentation of the activities creating customer value.');

  AgileDictionary.addWord('Velocity', 'A historical measure of the number of story points a team completes in a sprint.');

  AgileDictionary.addWord('Visual controls', 'The methods to see and manage the real-time flow of a value stream.');

  AgileDictionary.addWord('Wait Time', 'The time an asset is waiting and not being used to create customer value.');

  AgileDictionary.addWord('Wall clock time', 'The continuous measure of time between two milestone events.');

  AgileDictionary.addWord('Waste', 'Anything that does not add to or support the creation of customer value. Note that waste is determined by the recipient of the product/service not the producer.  See the Seven Office Wastes.');

  AgileDictionary.addWord('Waterfall Project Management', 'An approach to project management named by the discrete gate handoffs from one project stage to the next.  Example waterfall stages are requirement, functional, design, develop, test, implement.');

  AgileDictionary.addWord('Work-in-process', 'Assets of a product or service that are currently in-work and not yet completed. For example batches of sales orders that are waiting in a queue to be processed are work-in-process. Also known as WIP.');

  AgileDictionary.addWord('Work', 'The execution of activities that consume resources and produce a product or service.');

  AgileDictionary.addWord('Workspace', 'The area where stakeholder value is created. The workspace is an important concept in Lean process improvement because it is the location where customer value is created.');

  AgileDictionary.addWord('Work time', 'The wall clock time necessary to apply assets to create value added work if there are no blockages or interruptions. For example, the total work time to perform data entry for an order may only be a half hour; although the total wall clock time from when the order arrived on the desk of the data entry person until the time it left (service time) might be 4 hours.');

  exports.Dictionary = AgileDictionary;

}).call(this);
