// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(source, target) {
    var prop, _results;

    target = target || global;
    _results = [];
    for (prop in source) {
      _results.push(target[prop] = source[prop]);
    }
    return _results;
  };

}).call(this);
