// Generated by CoffeeScript 1.6.2
(function() {
  var _;

  _ = require('./myunderscore');

  module.exports = {
    paging: function(query) {
      var limit, page, skip;

      page = query.page || 1;
      limit = query.limit || 5;
      skip = (page - 1) * 5;
      return {
        page: page,
        limit: limit,
        skip: skip
      };
    },
    pageCountCalc: function(list, pageSize) {
      var fractionalPages, itemCount, pageCount;

      pageCount = parseInt(list.length / pageSize);
      itemCount = list.length;
      fractionalPages = 0;
      if (list.length % pageSize > 0) {
        fractionalPages = 1;
      }
      pageCount += fractionalPages;
      return {
        pageCount: pageCount,
        itemCount: itemCount
      };
    },
    diffFilter: function(masterList, compareList, comparisonProperty, paging) {
      var comparisonProperties, filteredList, result;

      comparisonProperties = _.pluck(masterList, comparisonProperty);
      filteredList = _.difference(comparisonProperties, compareList);
      filteredList = _.skipTake(filteredList, paging);
      filteredList = _.filter(masterList, function(masterItem) {
        return _.contains(filteredList, masterItem[comparisonProperty]);
      });
      result = this.createPagedResult(filteredList, paging);
      return result;
    },
    createPagedResult: function(list, paging) {
      var pageInfo, result;

      pageInfo = this.pageCountCalc(list, paging.limit);
      result = {
        items: list,
        pageCount: pageInfo.pageCount,
        itemCount: pageInfo.itemCount
      };
      return result;
    }
  };

}).call(this);
