// Generated by CoffeeScript 1.3.3
(function() {
  var fw;

  fw = require('../../framework');

  'class LoginModule\n  constructor: (registerHandler, registerSubscriber) ->\n    console.log \'handler:\'\n    console.log registerHandler\n    console.log \'subscriber:\'\n    console.log registerSubscriber';


  fw.registerHandler('Login', function(loginCommand) {
    return console.log('here is the command:' + loginCommand);
  });

  fw.registerSubscriber('LoginCompleted', function(loginCompleted) {
    return console.log('it completed:' + loginCompleted);
  });

}).call(this);
