// Generated by CoffeeScript 1.3.3
(function() {
  var db;

  db = require('../../db');

  module.exports = {
    authenticate: function(credentials, callback) {
      var query;
      query = {
        from: 'AccountRegister',
        where: {
          $and: [
            {
              password: credentials.password
            }, {
              $or: [
                {
                  userName: credentials.userNameOrEmail
                }, {
                  email: credentials.userNameOrEmail
                }
              ]
            }
          ]
        },
        select: 'userName'
      };
      return db.find(query, function(users) {
        var exists;
        exists = users.length > 0;
        return callback(null, exists);
      });
    }
  };

}).call(this);
