// Generated by CoffeeScript 1.6.2
(function() {
  var modules, requiredir;

  requiredir = require('require-dir');

  modules = requiredir('./modules', {
    filter: '.*module\.*js',
    recurse: true
  });

  console.log(modules);

}).call(this);
