// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    modules: [],
    addModule: function(moduleName) {
      this.modules.push(moduleName);
      return console.log('module added:' + moduleName);
    },
    registerSubscriber: function(topic, subscriber) {
      console.log('reg subscriber:');
      console.log(topic);
      return console.log(subscriber);
    },
    registerHandler: function(message, handler) {
      console.log('reg handler');
      console.log(message);
      return console.log(handler);
    }
  };

}).call(this);
