// Generated by CoffeeScript 1.6.2
(function() {
  var _;

  _ = require('underscore');

  _.mixin({
    skipTake: function(array, options) {
      options = _.extend({
        skip: 0,
        limit: 0
      }, options || {});
      return _(array).chain().rest(options.skip).first(options.limit || array.length - options.skip).value();
    }
  });

  module.exports = _;

}).call(this);
