// Generated by CoffeeScript 1.6.2
(function() {
  var LearnlocityService, bus, db, svc;

  bus = require('./bus');

  db = require('./db');

  db.connect();

  LearnlocityService = (function() {
    function LearnlocityService() {
      this.NotifySourceClient = null;
      this.NotifyAllClients = null;
      this.Join = null;
      this.NotifyRoom = null;
      this._challenges = [];
      this._onlineMembers = [];
    }

    LearnlocityService.prototype.processMessage = function(messageName, messageConstructorArguments) {
      return bus.processMessage(messageName, messageConstructorArguments);
    };

    return LearnlocityService;

  })();

  svc = new LearnlocityService();

  module.exports = svc;

  require('./modules');

}).call(this);
